#!/bin/bash
# Quick reference for BioMniBench re-run

echo "============================================================"
echo "  BioMniBench Re-run Quick Reference"
echo "  Started: 2026-06-10 19:35:38"
echo "============================================================"
echo ""
echo "STATUS CHECK:"
echo "  Main process: ps -ef | grep rerun_failed_tasks"
echo "  PID file:     cat /tmp/biomnibench_rerun.pid"
echo "  Bun workers:  pgrep -af 'bun.*evaluation/cli' | wc -l"
echo ""
echo "LOGS:"
echo "  Main log:     tail -f /data/yjh/biomnibench-rerun-logs/MAIN_20260610_193538.log"
echo "  Monitor:      /data/yjh/my_claude_biomnibench/scripts/monitor_rerun.sh"
echo ""
echo "PROGRESS:"
echo "  Total runs:   find /data/yjh/biomnibench-runs-v2 -name run_summary.json | wc -l"
echo "  Target:       140 (53 baseline + 87 re-run)"
echo ""
echo "STOP (if needed):"
echo "  kill -TERM \$(cat /tmp/biomnibench_rerun.pid)"
echo "  pkill -f 'bun.*evaluation/cli'"
echo ""
echo "DOCS:"
echo "  Full report:  cat /data/yjh/my_claude_biomnibench/RERUN_REPORT.md"
echo "  Skills guide: cat /data/yjh/my_claude_biomnibench/SKILLS_GENERATION_GUIDE.md"
echo "============================================================"
